owner: UW-IUGA 
repo: status

sites:
  - name: IUGA Website
    url: https://iuga.info
  - name: IUGA Website (Staging)
    url: $WEB_APP_STAGING
    expectedStatusCodes:
      - 200
      - 201
      - 401
  - name: IUGA Website (Development)
    url: $WEB_APP_DEV
    expectedStatusCodes:
      - 200
      - 201
      - 401
  - name: IUGA Admin Console
    url: $WEB_ADMIN
    
status-website:
  cname: status.iuga.info
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/UW-IUGA/status/master/assets/iuga-image.jpg
  favicon: https://raw.githubusercontent.com/UW-IUGA/status/master/assets/favicon.ico
  name: IUGA Status
  introTitle: "**Informatics Undergraduate Association**"
  introMessage: IT Status Page
  navbar:
    - title: Status
      href: /
