owner: UW-IUGA 
repo: status

sites:
  - name: IUGA Website
    url: https://iuga.info
    
status-website:
  cname: status.iuga.info
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/UW-IUGA/status/master/assets/iuga-image.jpg
  favicon: https://raw.githubusercontent.com/UW-IUGA/status/master/assets/favicon.ico
  name: IUGA Status
  introTitle: "**Informatics Undergraduate Association**"
  introMessage: IT Status Page
  navbar:
    - title: Status
      href: /
