owner: UW-IUGA 
repo: status

sites:
  - name: IUGA Website
    url: https://iuga.info
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  cname: status.iuga.info
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: IUGA Status
  introTitle: "**Informatics Undergraduate Association**"
  introMessage: IT Status Page
  navbar:
    - title: Status
      href: /
